import { isAbsolute, posix, relative, resolve, sep, win32 } from 'path'

const CONTROL_CHARS = /[\u0000-\u001f\u007f]/
const PATH_SEPARATORS = /[\\/]/
const TOOL_KEY = /^[A-Za-z0-9][A-Za-z0-9._-]*$/

export function validatePathSegment(value: string, label: string): string {
  if (typeof value !== 'string') {
    throw new Error(`${label} must be a string`)
  }
  const normalized = value.trim()
  if (
    normalized.length === 0 ||
    normalized === '.' ||
    normalized === '..' ||
    PATH_SEPARATORS.test(normalized) ||
    CONTROL_CHARS.test(normalized)
  ) {
    throw new Error(`invalid ${label}: ${value}`)
  }
  return normalized
}

/** Validate a frontmatter/directory-derived skill identity before using it in paths. */
export function validateSkillName(name: string): string {
  return validatePathSegment(name, 'skill name')
}

/** Custom and built-in tool keys are identifiers, not paths. */
export function validateToolKey(key: string): string {
  const normalized = validatePathSegment(key, 'tool key')
  if (!TOOL_KEY.test(normalized)) {
    throw new Error(`invalid tool key: ${key}`)
  }
  return normalized
}

/** Backup ids are single directory names generated by createBackup. */
export function validateBackupId(backupId: string): string {
  return validatePathSegment(backupId, 'backup id')
}

/** Require and normalize an absolute filesystem path received across a boundary. */
export function assertAbsolutePath(value: string, label: string): string {
  if (typeof value !== 'string' || !isAbsolute(value)) {
    throw new Error(`${label} must be an absolute path`)
  }
  return resolve(value)
}

/**
 * Resolve path segments beneath root and reject absolute/parent traversal.
 * This is a lexical confinement check; callers still decide whether symlinks are allowed.
 */
export function resolveWithin(root: string, ...segments: string[]): string {
  const rootPath = assertAbsolutePath(root, 'root')
  for (const segment of segments) {
    if (isAbsolute(segment)) {
      throw new Error(`absolute child path is not allowed: ${segment}`)
    }
  }
  const candidate = resolve(rootPath, ...segments)
  const rel = relative(rootPath, candidate)
  if (rel === '..' || rel.startsWith(`..${sep}`) || isAbsolute(rel)) {
    throw new Error(`path escapes root: ${candidate}`)
  }
  return candidate
}

/** Cross-platform lexical containment check, including Windows paths in tests. */
export function isPathWithin(root: string, candidate: string): boolean {
  const usesWindowsSyntax =
    /^(?:[A-Za-z]:[\\/]|\\\\)/.test(root) ||
    /^(?:[A-Za-z]:[\\/]|\\\\)/.test(candidate)
  const pathApi = usesWindowsSyntax ? win32 : posix
  const rel = pathApi.relative(pathApi.resolve(root), pathApi.resolve(candidate))
  return rel.length > 0 && rel !== '..' && !rel.startsWith(`..${pathApi.sep}`) && !pathApi.isAbsolute(rel)
}
